### ISSUE TITLE
Using QNetwork fails to compile

### ISSUE THREAD

**Issue by aebruno** [therecipe/qt#229]
Using QNetwork via `github.com/therecipe/qt/network` fails to compile. Here's the errors:

```
../../therecipe/qt/network/network-minimal.cpp: In function 'int QSsl_TlsV1_0OrLater_Type()':
../../therecipe/qt/network/network-minimal.cpp:622:9: error: 'TlsV1_0OrLater' is not a member of 'QSsl'
  return QSsl::TlsV1_0OrLater;
         ^
../../therecipe/qt/network/network-minimal.cpp: In function 'int QSsl_TlsV1_1OrLater_Type()':
../../therecipe/qt/network/network-minimal.cpp:627:9: error: 'TlsV1_1OrLater' is not a member of 'QSsl'
  return QSsl::TlsV1_1OrLater;
         ^
../../therecipe/qt/network/network-minimal.cpp: In function 'int QSsl_TlsV1_2OrLater_Type()':
../../therecipe/qt/network/network-minimal.cpp:632:9: error: 'TlsV1_2OrLater' is not a member of 'QSsl'
  return QSsl::TlsV1_2OrLater;
         ^
```

Looks like qtminimal has an issue with this enum and perhaps the empty values?

```xml
<enum threadsafety="unspecified" name="SslProtocol" fullname="QSsl::SslProtocol" href="qssl.html#SslProtocol-enum" status="active" access="public" location="qssl.h" filepath="/home/qt/work/qt/tqtc-qt5/qtbase/src/network/ssl/qssl.h" lineno="77">
    <value name="SslV3" value="0"/>
    <value name="SslV2" value="1"/>
    <value name="TlsV1_0" value="2"/>
    <value name="TlsV1" value="TlsV1_0"/>
    <value name="TlsV1_1" value=""/>
    <value name="TlsV1_2" value=""/>
    <value name="AnyProtocol" value=""/>
    <value name="TlsV1SslV3" value=""/>
    <value name="SecureProtocols" value=""/>
    <value name="TlsV1_0OrLater" value=""/>
    <value name="TlsV1_1OrLater" value=""/>
    <value name="TlsV1_2OrLater" value=""/>
    <value name="UnknownProtocol" value="-1"/>
```

Here's the generated cpp code:

```cpp
int QSsl_TlsV1_0OrLater_Type()
{
    return QSsl::TlsV1_0OrLater;
}

int QSsl_TlsV1_1OrLater_Type()
{
    return QSsl::TlsV1_1OrLater;
}

int QSsl_TlsV1_2OrLater_Type()
{
    return QSsl::TlsV1_2OrLater;
}
```

As a workaround I just set these to return 0 as they're not being used. Any thoughts on how to fix?

**Comment by therecipe** [comment]
Should be fixed with https://github.com/therecipe/qt/commit/6ed0e19c1520c97b43b9cba41899cf9904d72b95

I made a minor change to always include the "QSsl" header file: https://github.com/therecipe/qt/blob/master/internal/binding/templater/template_cpp.go#L363

This probably fails currently for you (with qtminimal):

```go
package main

import _ "github.com/therecipe/qt/network"

func main() {

}
```

but it should work after the change.

**Comment by aebruno** [comment]
Looks like it's still broken. I'm using that latest commit cc0c5bf2f27659e5956687c3bf66d1f7b4ddd40d. Also should have mentioned I'm compiling for sailfish on Qt 5.2. Here's the error:

```
../../therecipe/qt/network/network-minimal.cpp: In function 'int QSsl_TlsV1_0OrLater_Type()':
../../therecipe/qt/network/network-minimal.cpp:622:9: error: 'TlsV1_0OrLater' is not a member of 'QSsl'
  return QSsl::TlsV1_0OrLater;
         ^
../../therecipe/qt/network/network-minimal.cpp: In function 'int QSsl_TlsV1_1OrLater_Type()':
../../therecipe/qt/network/network-minimal.cpp:627:9: error: 'TlsV1_1OrLater' is not a member of 'QSsl'
  return QSsl::TlsV1_1OrLater;
         ^
../../therecipe/qt/network/network-minimal.cpp: In function 'int QSsl_TlsV1_2OrLater_Type()':
../../therecipe/qt/network/network-minimal.cpp:632:9: error: 'TlsV1_2OrLater' is not a member of 'QSsl'
  return QSsl::TlsV1_2OrLater;
```

Verified the generated network-minimal.cpp does contain:

```cpp
#include <QSsl>
```

**Comment by therecipe** [comment]
Ah, okay I just tested it with 5.6 on the desktop.

The preprocessor will take care of it now with: https://github.com/therecipe/qt/commit/c6ada02b904734c7f78a8032acd2e6fee3e58dba

So this should work now after qtminimal:

```go
package main

import (
	_ "github.com/therecipe/qt/core"
	_ "github.com/therecipe/qt/dbus"
	_ "github.com/therecipe/qt/gui"
	_ "github.com/therecipe/qt/multimedia"
	_ "github.com/therecipe/qt/network"
	_ "github.com/therecipe/qt/positioning"
	_ "github.com/therecipe/qt/qml"
	_ "github.com/therecipe/qt/quick"
	_ "github.com/therecipe/qt/sensors"
	_ "github.com/therecipe/qt/sql"
	_ "github.com/therecipe/qt/svg"
	_ "github.com/therecipe/qt/xml"
	_ "github.com/therecipe/qt/xmlpatterns"
)

func main() {

}
```

Tested with Qt 5.8 (because there is no moc needed) and version 1611 of the Sailfish sdk on darwin.

**Comment by aebruno** [comment]
Excellent. Works great. Thanks very much! Feel free to close this out.
