### ISSUE TITLE
'argcs' was not declared in this scope

### ISSUE THREAD

**Issue by AnyCPU** [therecipe/qt#358]
Hi,

I have tried to build a static version and now I see such error:

> # github.com/therecipe/qt/gui
>..\..\..\..\gui\gui-minimal.cpp: In function 'void* QGuiApplication_NewQGuiApplication(int, char*)':
>..\..\..\..\gui\gui-minimal.cpp:131:31: error: 'argcs' was not declared in this scope
>  return new MyQGuiApplication(argcs, argvs);

**Comment by AnyCPU** [comment]
I use: windows, msys2, go 1.8.4

**Comment by AnyCPU** [comment]
It looks like a typo in sources

**Comment by therecipe** [comment]
Hey

Could you maybe post the function body of `QGuiApplication_NewQGuiApplication` from `gui-minimal.cpp`?

**Comment by AnyCPU** [comment]
> void* QGuiApplication_NewQGuiApplication(int argc, char* argv)
{
	return new MyQGuiApplication(argcs, argvs);
}

**Comment by therecipe** [comment]
Thanks, yeah that doesn't look right.
It should look more like this actually:

```cpp

void* QGuiApplication_NewQGuiApplication(int argc, char* argv)
{
static int argcs = argc;
static char** argvs = static_cast<char**>(malloc(argcs * sizeof(char*)));

QList<QByteArray> aList = QByteArray(argv).split('|');
for (int i = 0; i < argcs; i++)
	argvs[i] = (new QByteArray(aList.at(i)))->data();

return new MyQGuiApplication(argcs, argvs);
}
```

Also did you test if it works with the dynamically linked ("shared") version?

**Comment by AnyCPU** [comment]
No, I didn't. I think I could do it tomorrow.

**Comment by therecipe** [comment]
Okay, I will try to reproduce it in the meantime.
There seem to have been a few Qt related changes lately to the mingw-packages repo, so maybe one of those broke it.

**Comment by AnyCPU** [comment]
Having tried a dynamic build I got:

> ERRORfailed to run command                         cmd="xcopy C:\msys64\mingw64\bin\libicudt57.dll ...\gopath\src\github.com\therecipe\qt\internal\examples\qml\application\deploy\windows" env= error="exit status 4" func=RunCmdOptional name="copy libicudt57 for windows on windows"
File not found - libicudt57.dll
0 File(s) copied


But I found the libicudt58.dll in the bin directory.

**Comment by therecipe** [comment]
>But I found the libicudt58.dll in the bin directory.

Ah, this means they probably switched to Qt 5.9
I will look into it.

**Comment by therecipe** [comment]
Okay, seems like the dynamic version is on 5.9 and the static one still on 5.8
I will fix this.

**Comment by therecipe** [comment]
Okay, tested it and there was an issue with the 64bit static version.
And the shared versions complained about the missing icu* libs.

Both issues should be fixed now with: https://github.com/therecipe/qt/commit/9720239949e766fb495002290a55a301a2e4f9e9

Could you try it again?

**Comment by AnyCPU** [comment]
Hello @therecipe  I have tried a clean install, but there is still the same trouble.

> void* QGuiApplication_NewQGuiApplication(int argc, char* argv)
> {
> 	return new MyQGuiApplication(argcs, argvs);
> }

`gui-minimal.cpp: In function 'void* QGuiApplication_NewQGuiApplication(int, char*)':
gui-minimal.cpp:131:31: error: 'argcs' was not declared in this scope
  return new MyQGuiApplication(argcs, argvs);
                               ^~~~~
gui-minimal.cpp:131:38: error: 'argvs' was not declared in this scope
  return new MyQGuiApplication(argcs, argvs);
                                      ^~~~~
gui-minimal.cpp:129:46: warning: unused parameter 'argc' [-Wunused-parameter]
 void* QGuiApplication_NewQGuiApplication(int argc, char* argv)
                                              ^~~~
gui-minimal.cpp:129:58: warning: unused parameter 'argv' [-Wunused-parameter]
 void* QGuiApplication_NewQGuiApplication(int argc, char* argv)`

**Comment by AnyCPU** [comment]
I added the line
```
 || parser.State.ClassMap[function.ClassName()].IsSubClassOf("QGuiApplication") 
```

 into the ..\src\github.com\therecipe\qt\internal\binding\templater\function_cpp.go

```func cppFunctionBodyInternal(function *parser.Function) string {

	switch function.Meta {
	case parser.CONSTRUCTOR:
		{
			return fmt.Sprintf("%v\treturn new %v%v(%v);",
				func() string {
					if parser.State.ClassMap[function.ClassName()].IsSubClassOf("QCoreApplication") || parser.State.ClassMap[function.ClassName()].IsSubClassOf("QGuiApplication") {
```
And got
```
void* QGuiApplication_NewQGuiApplication(int argc, char* argv)
{
static int argcs = argc;
static char** argvs = static_cast<char**>(malloc(argcs * sizeof(char*)));

QList<QByteArray> aList = QByteArray(argv).split('|');
for (int i = 0; i < argcs; i++)
	argvs[i] = (new QByteArray(aList.at(i)))->data();

return new MyQGuiApplication(argcs, argvs);
}
```

**Comment by AnyCPU** [comment]
But now I keep getting another errors:
```
core-minimal.cpp: In function 'void QObject_ConnectObjectNameChanged(void*)':
core-minimal.cpp:1365:122: error: invalid static_cast from type 'void (QObject::*)(const QString&, QObject::QPrivateSignal)' to type 'void (QObject::*)(const QString&)'
  QObject::connect(static_cast<QObject*>(ptr), static_cast<void (QObject::*)(const QString &)>(&QObject::objectNameChanged), static_cast<MyQObject*>(ptr), static_cast<void (MyQObject::*)(const QString &)>(&MyQObject::Signal_ObjectNameChanged));
                                                                                                                          ^
core-minimal.cpp: In function 'void QObject_DisconnectObjectNameChanged(void*)':core-minimal.cpp:1370:125: error: invalid static_cast from type 'void (QObject::*)(const QString&, QObject::QPrivateSignal)' to type 'void (QObject::*)(const QString&)'
  QObject::disconnect(static_cast<QObject*>(ptr), static_cast<void (QObject::*)(const QString &)>(&QObject::objectNameChanged), static_cast<MyQObject*>(ptr), static_cast<void (MyQObject::*)(const QString &)>(&MyQObject::Signal_ObjectNameChanged));
                                                                                                                             ^
core-minimal.cpp: In function 'void QObject_ObjectNameChanged(void*, char*)':
core-minimal.cpp:1375:67: error: no matching function for call to 'QObject::objectNameChanged(QString)'
  static_cast<QObject*>(ptr)->objectNameChanged(QString(objectName));
                                                                   ^
In file included from C:/msys64/mingw64/qt5-static/include/QtCore/qabstracteventdispatcher.h:43:0,
                 from C:/msys64/mingw64/qt5-static/include/QtCore/QAbstractEventDispatcher:1,
                 from core-minimal.cpp:9:
C:/msys64/mingw64/qt5-static/include/QtCore/qobject.h:395:10: note: candidate: void QObject::objectNameChanged(const QString&, QObject::QPrivateSignal)
     void objectNameChanged(const QString &objectName, QPrivateSignal);
          ^~~~~~~~~~~~~~~~~
C:/msys64/mingw64/qt5-static/include/QtCore/qobject.h:395:10: note:   candidate expects 2 arguments, 1 provided
```
and
```
core-minimal.cpp: In function 'void QSocketNotifier_ConnectActivated(void*)':
core-minimal.cpp:2299:126: error: invalid static_cast from type 'void (QSocketNotifier::*)(int, QSocketNotifier::QPrivateSignal)' to type 'void (QSocketNotifier::*)(int)'
  QObject::connect(static_cast<QSocketNotifier*>(ptr), static_cast<void (QSocketNotifier::*)(int)>(&QSocketNotifier::activated), static_cast<MyQSocketNotifier*>(ptr), static_cast<void (MyQSocketNotifier::*)(int)>(&MyQSocketNotifier::Signal_Activated));
                                                                                                                              ^
core-minimal.cpp: In function 'void QSocketNotifier_DisconnectActivated(void*)':
core-minimal.cpp:2304:129: error: invalid static_cast from type 'void (QSocketNotifier::*)(int, QSocketNotifier::QPrivateSignal)' to type 'void (QSocketNotifier::*)(int)'
  QObject::disconnect(static_cast<QSocketNotifier*>(ptr), static_cast<void (QSocketNotifier::*)(int)>(&QSocketNotifier::activated), static_cast<MyQSocketNotifier*>(ptr), static_cast<void (MyQSocketNotifier::*)(int)>(&MyQSocketNotifier::Signal_Activated));
                                                                                                                                 ^
core-minimal.cpp: In function 'void QSocketNotifier_Activated(void*, int)':
core-minimal.cpp:2309:54: error: no matching function for call to 'QSocketNotifier::activated(int&)'
  static_cast<QSocketNotifier*>(ptr)->activated(socket);
                                                      ^
In file included from C:/msys64/mingw64/qt5-static/include/QtCore/QSocketNotifier:1:0,
                 from core-minimal.cpp:53:
C:/msys64/mingw64/qt5-static/include/QtCore/qsocketnotifier.h:68:10: note: candidate: void QSocketNotifier::activated(int, QSocketNotifier::QPrivateSignal)
     void activated(int socket, QPrivateSignal);
          ^~~~~~~~~
```
But also it is able to deploy this example - github.com\therecipe\qt\internal\examples\qml\application

**Comment by AnyCPU** [comment]
So the qtsetup fails on the `INFO[0167] testing qml\drawer_nav_x` command

**Comment by AnyCPU** [comment]
I have found in the qt docs, but I do not know what it means in this case
```
void QObject::objectNameChanged(const QString &objectName)
This signal is emitted after the object's name has been changed. The new object name is passed as objectName.
Note: This is a private signal. It can be used in signal connections but cannot be emitted by the user.
Note: Notifier signal for property objectName. 
```

**Comment by therecipe** [comment]
Mh, I suspect that the setup is probably misconfigured.

I tested it on Win 7 64bit with the mingw64 shell.
And the latest commit `02f7c45f78fdce4d3f7f04d81f44cc8b479af3aa`.
There was also no need to set/export anything beside `QT_MSYS2_STATIC=true`

```
$GOPATH/bin/qtsetup.exe
running: 'qtsetup prep'
running: 'qtsetup check windows' [docker=false]
GOOS:                        'windows'
GOARCH:                      'amd64'
GOVERSION:                   'go1.8.3'
GOROOT:                   *  'C:\Go\'
GOPATH:                      'C:\Users\user\go'
GOBIN:                       'C:\Users\user\go\bin'
QT_HASH:                     'please install git'
QT_VERSION:                  '5.8.0'
QT_VERSION_MAJOR:            '5.8'
QT_DIR:                      'C:\Qt\Qt5.8.0'
QT_STUB:                     'true'
QT_DEBUG:                    'false'
QT_QMAKE_DIR:                ''
QT_WEBKIT:                   'false'
QT_MSYS2:                    'true'
QT_MSYS2_DIR:                'C:\msys64\mingw64'
QT_MSYS2_ARCH:               'amd64'
QT_MSYS2_STATIC:          *  'true'
```

```
$ pacman -Qe
bash 4.4.012-1
bash-completion 2.3-1
bsdcpio 3.2.1-1
bsdtar 3.2.1-1
bzip2 1.0.6-2
catgets 1.1-2
coreutils 8.25-1
crypt 1.3-1
curl 7.50.3-1
dash 0.5.9.1-1
file 5.28-2
filesystem 2017.05-1
findutils 4.6.0-1
flex 2.6.1-1
gawk 4.1.4-1
gcc-libs 5.3.0-3
grep 2.26-1
gzip 1.8-1
inetutils 1.9.2-1
info 6.1-1
less 481-1
lndir 1.0.3-1
mingw-w64-i686-qt-creator 4.3.0-1
mingw-w64-i686-qt5 5.9.0-1
mingw-w64-i686-qt5-static 5.8.0-1
mingw-w64-x86_64-qt-creator 4.3.0-1
mingw-w64-x86_64-qt5 5.9.0-1
mingw-w64-x86_64-qt5-static 5.8.0-1
mintty 1~2.7.7-1
msys2-keyring r9.397a52e-1
msys2-launcher-git 0.3.32.56c2ba7-2
msys2-runtime 2.7.0-1
nano 2.8.2-1
ncurses 6.0.20161001-1
pacman 5.0.1-2
pacman-mirrors 20160112-1
pactoys-git r2.07ca37f-1
pax-git 20140703.2.1.g469552a-1
pkgfile 15-1
rebase 4.4.2-1
sed 4.2.2-2
tftp-hpa 5.2-1
time 1.7-1
ttyrec 1.0.8-1
tzcode 2015.e-1
util-linux 2.26.2-1
which 2.21-2
```

**Comment by AnyCPU** [comment]
@therecipe 

time="2017-06-17T20:38:34+03:00" level=info msg="GOOS:                        'windows'"
time="2017-06-17T20:38:34+03:00" level=info msg="GOARCH:                      'amd64'"
time="2017-06-17T20:38:34+03:00" level=info msg="GOVERSION:                   'go1.9beta1'"
time="2017-06-17T20:38:34+03:00" level=info msg="GOROOT:                   *  'C:\Go\'"
time="2017-06-17T20:38:34+03:00" level=info msg="GOPATH:                   *  'D:/Dev/Private/gopath'"
time="2017-06-17T20:38:34+03:00" level=info msg="GOBIN:                       'D:\Dev\Private\gopath\bin'"
time="2017-06-17T20:38:34+03:00" level=info msg="QT_HASH:                     '02f7c45f78fdce4d3f7f04d81f44cc8b479af3aa'"
time="2017-06-17T20:38:34+03:00" level=info msg="QT_VERSION:                  '5.8.0'"
time="2017-06-17T20:38:34+03:00" level=info msg="QT_VERSION_MAJOR:            '5.8'"
time="2017-06-17T20:38:34+03:00" level=info msg="QT_DIR:                      'C:\Qt\Qt5.8.0'"
time="2017-06-17T20:38:34+03:00" level=info msg="QT_STUB:                     'true'"
time="2017-06-17T20:38:34+03:00" level=info msg="QT_DEBUG:                    'false'"
time="2017-06-17T20:38:34+03:00" level=info msg="QT_QMAKE_DIR:                ''"
time="2017-06-17T20:38:34+03:00" level=info msg="QT_WEBKIT:                   'false'"
time="2017-06-17T20:38:34+03:00" level=info msg="QT_MSYS2:                 *  'true'"
time="2017-06-17T20:38:34+03:00" level=info msg="QT_MSYS2_DIR:                'C:\msys64\mingw64'"
time="2017-06-17T20:38:34+03:00" level=info msg="QT_MSYS2_ARCH:            *  'amd64'"

```
$ pacman -Qe
bash 4.4.012-1
bash-completion 2.5-1
bsdcpio 3.3.1-1
bsdtar 3.3.1-1
bzip2 1.0.6-2
catgets 1.1-2
coreutils 8.26-1
crypt 1.4-1
curl 7.54.0-1
dash 0.5.9.1-1
file 5.30-1
filesystem 2017.05-1
findutils 4.6.0-1
flex 2.6.4-1
gawk 4.1.4-2
gcc-libs 6.3.0-1
grep 3.0-1
gzip 1.8-1
inetutils 1.9.4-1
info 6.3-1
less 481-1
lndir 1.0.3-1
mingw-w64-x86_64-gcc 6.3.0-3
mingw-w64-x86_64-jasper 2.0.13-1
mingw-w64-x86_64-openssl 1.0.2.l-1
mingw-w64-x86_64-qt5-static 5.8.0-1
mintty 1~2.7.7-1
msys2-keyring r9.397a52e-1
msys2-launcher-git 0.3.32.56c2ba7-2
msys2-runtime 2.7.0-1
ncurses 6.0.20170527-1
pacman 5.0.1-2
pacman-mirrors 20160112-1
pactoys-git r2.07ca37f-1
pax-git 20161104.2-1
pkgfile 17-1
rebase 4.4.2-1
sed 4.4-2
tftp-hpa 5.2-1
time 1.7-1
ttyrec 1.0.8-1
tzcode 2017.b-1
util-linux 2.26.2-1
which 2.21-2
```

**Comment by AnyCPU** [comment]
I did a clean install again and got

```
# github.com/therecipe/qt/gui
gui-minimal.cpp: In function 'void* QGuiApplication_NewQGuiApplication(int, char*)':
gui-minimal.cpp:131:31: error: 'argcs' was not declared in this scope
  return new MyQGuiApplication(argcs, argvs);
                               ^~~~~
gui-minimal.cpp:131:38: error: 'argvs' was not declared in this scope
  return new MyQGuiApplication(argcs, argvs);
                                      ^~~~~
gui-minimal.cpp:129:46: warning: unused parameter 'argc' [-Wunused-parameter]
 void* QGuiApplication_NewQGuiApplication(int argc, char* argv)
                                              ^~~~
gui-minimal.cpp:129:58: warning: unused parameter 'argv' [-Wunused-parameter]
 void* QGuiApplication_NewQGuiApplication(int argc, char* argv)
```

**Comment by therecipe** [comment]
Seems like you probably also need to install `mingw-w64-x86_64-qt5` and/or `mingw-w64-x86_64-qt-creator`. I'm not quit sure which one is mandatory, but I think it's `mingw-w64-x86_64-qt5`.

**Comment by AnyCPU** [comment]
@therecipe  is it a requirements that I need to install both static and dynamic qt's runtimes?
It tried and tests seem ok,

**Comment by therecipe** [comment]
Yeah, it's necessary at the moment.
But I will review it.

**Comment by AnyCPU** [comment]
@therecipe  ok, thank you. I think this issue can be closed.

**Comment by therecipe** [comment]
:) Okay, I also think that the dependency on `mingw-w64-x86_64-qt5` is gone now as well with https://github.com/therecipe/qt/commit/d40d963b11f43295122327888925576319ee40fa

**Comment by AnyCPU** [comment]
@therecipe I have tried the https://github.com/therecipe/qt/commit/d40d963b11f43295122327888925576319ee40fa . No luck, I got the same error about static cast and QPrivateSignal in the *objectNameChanged.

**Comment by therecipe** [comment]
Mh, could you maybe run `go clean -i github.com/therecipe/qt/...` then remove `src/github.com/therecipe/qt`, then clone or "go get" the repo again and then run `qtsetup.exe prep` inside the cmd. After that you should be able to use`qtsetup` as usual in mingw64.

Sometimes there are some old qt* binaries left somewhere and it won't work therefore.

**Comment by AnyCPU** [comment]
@therecipe  I have tried, still no luck. The Basic layout examples was compiled successfully, but then following example wasn't compiled because of the objectNameChanged problem.

**Comment by therecipe** [comment]
Mh, okay. I will setup a fresh Win 10 vm and look into it again.
