### ISSUE TITLE
qtsetup failing with QGstreamerV4L2Input file not found

### ISSUE THREAD

**Issue by JasonWeise** [therecipe/qt#877]
Hi

I posted in another issue about a problem I was having with being able to compile *.ui files with the new uic features and in the meantime thought I would try and update my installation therecipe/qt

I originally tried to update which failed so started with a fresh install and now the latest version fails on "installing full qt/core" with
```
core.cpp:74:19: fatal error: 'QGstreamerV4L2Input' file not found.
```

This was on MacOS (Mojave) with a fresh github pull from this repo and running qtsetup.

My install from about 3 weeks ago went fine so I figure something has changed in the repo to cause this.

PS. I am using QT 5.13 Beta 4
I was using QT 5.13 Beta 3 on the last install without issue.

Thanks in advance.

**Comment by therecipe** [comment]
Hey

I looked into this and it seems like the `*.index` files which are needed to generate the binding are somewhat broken in the latest beta. But you can work around this for now by using
`QT_VERSION=5.13.0 QT_API=5.12.0` which will let qtdeploy/qtsetup link against Qt 5.13 while using the "old" Qt 5.12 index files from this repo.

**Comment by JasonWeise** [comment]
thanks heaps.
I have upgraded to 5.13.0-RC now and it still has the same issue so will just us the QT_API work around
Hopefully the index files will be fixed by QT before 5.13.0-GA

**Comment by therecipe** [comment]
No problem :)
Yeah I hope so as well, it would be quite tedious to fix it by hand.
But they also always seemed to re-generate the docs one last time before releasing, so it will probably go well.

**Comment by JasonWeise** [comment]
@therecipe 
Looks like the docs weren't re-generated :(
Fresh Mac (brand new 27"), fresh install of QT 5.13.0 (GA - its out now) latest Go and latest from this repo and exactly same error on qtsetup without `QT_API=5.12.0`

**Comment by bh90210** [comment]
had the same issue with qt 5.13.0, it is failing me with 
```
INFO[1062] installing full qt/core                      
github.com/therecipe/qt
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:74:10: fatal error: QGstreamerV4L2Input: No such file or directory
 #include <QGstreamerV4L2Input>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

ERRO[1694] failed to install 'core'; aborting setup  
```

downgrading to 5.12.2 :crossed_fingers:

**Comment by therecipe** [comment]
@JasonWeise @bh90210 
5.13.0 should work now with https://github.com/therecipe/qt/commit/af32cfd0e0aa8943a622f44f321e76d41237db77 after blacklisting the internal classes which where wrongly exposed by the *.index files
I only tested it on macOS for now though, and also haven't pushed the changes to fix the examples yet.

**Comment by jacobc22** [comment]
I'm still getting this error as of the latest commit when running qtsetup with 5.13.0 and Windows 10 64bit

`time="2019-06-28T15:29:00-05:00" level=info msg="installing full qt/core"
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:74:10: fatal error: QGstreamerV4L2Input: No such file or directory
 #include <QGstreamerV4L2Input>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

time="2019-06-28T15:31:43-05:00" level=error msg="failed to install 'core'; aborting setup"`
