### ISSUE TITLE
Windows x64 winstallation problem

### ISSUE THREAD

**Issue by Hanan-Natan** [therecipe/qt#909]
Following the Official version path I installed Qt 5.13.0.
When i run `%GOPATH%\bin\qtsetup.exe` i get the following output:
```
E:\>%GOPATH%\bin\qtsetup.exe
time="2019-07-19T09:58:06+03:00" level=warning msg="failed to create qtenv.bat symlink in your PATH (C:\\Users\\user1\\scoop\\apps\\go\\current\\bin\\qtenv.bat); please use E:\\WorkFiles\\Dev\\Libs\\Qt\\5.13.0\\mingw73_64\\bin\\qtenv2.bat instead"
time="2019-07-19T09:58:06+03:00" level=info msg="running: 'qtsetup prep'"
time="2019-07-19T09:58:06+03:00" level=warning msg="failed to create qtrcc symlink in your PATH (C:\\Users\\user1\\scoop\\apps\\go\\current\\bin\\qtrcc.exe); please use E:\\WorkFiles\\Dev\\GoProjects\\bin\\qtrcc.exe instead"
time="2019-07-19T09:58:06+03:00" level=warning msg="failed to create qtmoc symlink in your PATH (C:\\Users\\user1\\scoop\\apps\\go\\current\\bin\\qtmoc.exe); please use E:\\WorkFiles\\Dev\\GoProjects\\bin\\qtmoc.exe instead"
time="2019-07-19T09:58:06+03:00" level=warning msg="failed to create qtminimal symlink in your PATH (C:\\Users\\user1\\scoop\\apps\\go\\current\\bin\\qtminimal.exe); please use E:\\WorkFiles\\Dev\\GoProjects\\bin\\qtminimal.exe instead"
time="2019-07-19T09:58:06+03:00" level=warning msg="failed to create qtdeploy symlink in your PATH (C:\\Users\\user1\\scoop\\apps\\go\\current\\bin\\qtdeploy.exe); please use E:\\WorkFiles\\Dev\\GoProjects\\bin\\qtdeploy.exe instead"
time="2019-07-19T09:58:06+03:00" level=info msg="running: 'qtsetup check windows' [docker=false] [vagrant=false]"
time="2019-07-19T09:58:06+03:00" level=info msg="GOOS:                        'windows'"
time="2019-07-19T09:58:06+03:00" level=info msg="GOARCH:                      'amd64'"
time="2019-07-19T09:58:06+03:00" level=info msg="GOVERSION:                   'go1.12.7'"
time="2019-07-19T09:58:06+03:00" level=info msg="GOROOT:                   *  'C:\\Users\\user1\\scoop\\apps\\go\\current'"
time="2019-07-19T09:58:06+03:00" level=info msg="GOPATH:                   *  'E:\\WorkFiles\\Dev\\GoProjects'"
time="2019-07-19T09:58:06+03:00" level=info msg="GOBIN:                       'E:\\WorkFiles\\Dev\\GoProjects\\bin'"
time="2019-07-19T09:58:06+03:00" level=info msg="GOMOD:                       ''"
time="2019-07-19T09:58:06+03:00" level=info msg="QT_HASH:                     'a9acd1ab63c1365681bac0d31ce994989a9dd433'"
time="2019-07-19T09:58:06+03:00" level=info msg="QT_API:                      ''"
time="2019-07-19T09:58:06+03:00" level=info msg="QT_VERSION:                  '5.13.0'"
time="2019-07-19T09:58:06+03:00" level=info msg="QT_DIR:                   *  'E:\\WorkFiles\\Dev\\Libs\\Qt'"
time="2019-07-19T09:58:06+03:00" level=info msg="QT_STUB:                     'false'"
time="2019-07-19T09:58:06+03:00" level=info msg="QT_DEBUG:                    'false'"
time="2019-07-19T09:58:06+03:00" level=info msg="QT_QMAKE_DIR:                ''"
time="2019-07-19T09:58:06+03:00" level=info msg="QT_WEBKIT:                   'false'"
time="2019-07-19T09:58:06+03:00" level=info msg="QT_DEBUG_CONSOLE:            'false'"
time="2019-07-19T09:58:06+03:00" level=info msg="QT_MSYS2:                    'false'"
time="2019-07-19T09:58:06+03:00" level=info msg="running: 'qtsetup generate windows' [docker=false] [vagrant=false]"
time="2019-07-19T09:58:16+03:00" level=info msg="generating full qt/core"
time="2019-07-19T09:58:30+03:00" level=info msg="generating full qt/androidextras"
time="2019-07-19T09:58:30+03:00" level=info msg="generating full qt/gui"
time="2019-07-19T09:58:48+03:00" level=info msg="generating full qt/network"
time="2019-07-19T09:58:53+03:00" level=info msg="generating full qt/xml"
time="2019-07-19T09:58:54+03:00" level=info msg="generating full qt/dbus"
time="2019-07-19T09:58:56+03:00" level=info msg="generating full qt/nfc"
time="2019-07-19T09:58:57+03:00" level=info msg="generating full qt/script"
time="2019-07-19T09:58:58+03:00" level=info msg="generating full qt/sensors"
time="2019-07-19T09:59:02+03:00" level=info msg="generating full qt/positioning"
time="2019-07-19T09:59:04+03:00" level=info msg="generating full qt/widgets"
time="2019-07-19T09:59:43+03:00" level=info msg="generating full qt/sql"
time="2019-07-19T09:59:45+03:00" level=info msg="generating full qt/qml"
time="2019-07-19T09:59:48+03:00" level=info msg="generating full qt/websockets"
time="2019-07-19T09:59:49+03:00" level=info msg="generating full qt/xmlpatterns"
time="2019-07-19T09:59:50+03:00" level=info msg="generating full qt/bluetooth"
time="2019-07-19T09:59:52+03:00" level=info msg="generating full qt/webchannel"
time="2019-07-19T09:59:53+03:00" level=info msg="generating full qt/svg"
time="2019-07-19T09:59:54+03:00" level=info msg="generating full qt/multimedia"
time="2019-07-19T10:00:09+03:00" level=info msg="generating full qt/quick"
time="2019-07-19T10:00:13+03:00" level=info msg="generating full qt/help"
time="2019-07-19T10:00:17+03:00" level=info msg="generating full qt/location"
time="2019-07-19T10:00:19+03:00" level=info msg="generating full qt/scripttools"
time="2019-07-19T10:00:19+03:00" level=info msg="generating full qt/uitools"
time="2019-07-19T10:00:20+03:00" level=info msg="generating full qt/winextras"
time="2019-07-19T10:00:21+03:00" level=info msg="generating full qt/testlib"
time="2019-07-19T10:00:21+03:00" level=info msg="generating full qt/serialport"
time="2019-07-19T10:00:22+03:00" level=info msg="generating full qt/serialbus"
time="2019-07-19T10:00:24+03:00" level=info msg="generating full qt/printsupport"
time="2019-07-19T10:00:26+03:00" level=info msg="generating full qt/designer"
time="2019-07-19T10:00:31+03:00" level=info msg="generating full qt/scxml"
time="2019-07-19T10:00:32+03:00" level=info msg="generating full qt/gamepad"
time="2019-07-19T10:00:33+03:00" level=info msg="generating full qt/purchasing"
time="2019-07-19T10:00:34+03:00" level=info msg="generating full qt/datavisualization    [GPLv3]"
time="2019-07-19T10:00:41+03:00" level=info msg="generating full qt/charts               [GPLv3]"
time="2019-07-19T10:00:50+03:00" level=info msg="generating full qt/virtualkeyboard      [GPLv3]"
time="2019-07-19T10:00:52+03:00" level=info msg="generating full qt/speech"
time="2019-07-19T10:00:53+03:00" level=info msg="generating full qt/quickcontrols2"
time="2019-07-19T10:00:53+03:00" level=info msg="generating full qt/sailfish"
time="2019-07-19T10:00:53+03:00" level=info msg="generating full qt/remoteobjects"
time="2019-07-19T10:00:55+03:00" level=info msg="running: 'qtsetup install windows' [docker=false] [vagrant=false]"
time="2019-07-19T10:00:55+03:00" level=info msg="installing full qt/core"
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
E:/WorkFiles/Dev/Libs/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Svg
E:/WorkFiles/Dev/Libs/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5MultimediaWidgets
E:/WorkFiles/Dev/Libs/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Designer
E:/WorkFiles/Dev/Libs/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5QuickWidgets
E:/WorkFiles/Dev/Libs/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Widgets
E:/WorkFiles/Dev/Libs/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Multimedia
E:/WorkFiles/Dev/Libs/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Quick
E:/WorkFiles/Dev/Libs/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Gui
E:/WorkFiles/Dev/Libs/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Qml
E:/WorkFiles/Dev/Libs/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5RemoteObjects
E:/WorkFiles/Dev/Libs/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Network
E:/WorkFiles/Dev/Libs/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5DBus
E:/WorkFiles/Dev/Libs/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Xml
E:/WorkFiles/Dev/Libs/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Core
collect2.exe: error: ld returned 1 exit status
# github.com/therecipe/qt/core
core.cpp: In constructor 'MyQSignalMapper::MyQSignalMapper(QObject*)':
core.cpp:18945:69: warning: 'QSignalMapper::QSignalMapper(QObject*)' is deprecated [-Wdeprecated-declarations]
  MyQSignalMapper(QObject *parent = Q_NULLPTR) : QSignalMapper(parent) {QSignalMapper_QSignalMapper_QRegisterMetaType();};
                                                                     ^
In file included from E:/WorkFiles/Dev/Libs/Qt/5.13.0/mingw73_64/include/QtCore/QSignalMapper:1:0,
                 from core.cpp:152:
E:/WorkFiles/Dev/Libs/Qt/5.13.0/mingw73_64/include/QtCore/qsignalmapper.h:56:28: note: declared here
     QT_DEPRECATED explicit QSignalMapper(QObject *parent = nullptr);
                            ^~~~~~~~~~~~~

time="2019-07-19T10:03:48+03:00" level=error msg="failed to install 'core'; aborting setup"
```

What am i missing?

**Comment by walkskyer** [comment]
I got the seam problem

**Comment by therecipe** [comment]
Hey

Sorry for the trouble, it seems like they changed some of the index files of the windows builds for some reason.

It should be fixed now with https://github.com/therecipe/qt/commit/37b08fcec7033f4e3ba23a8ed5e1320e277d094d#diff-555ed08e6d985548ca7df2b4cac4676e

**Comment by Hanan-Natan** [comment]
Hi,

It works!
Thank you!


There are some errors that might be related to other bugs. Here are the errors i get:
```
...
time="2019-08-08T21:16:37+03:00" level=info msg="installing full qt/script"
github.com/therecipe/qt/script
# github.com/therecipe/qt/script
script.cpp:32:10: fatal error: QScriptClass: No such file or directory
 #include <QScriptClass>
          ^~~~~~~~~~~~~~
compilation terminated.
...

time="2019-08-08T21:31:37+03:00" level=info msg="installing full qt/scripttools"
github.com/therecipe/qt/script
# github.com/therecipe/qt/script
script.cpp:32:10: fatal error: QScriptClass: No such file or directory
 #include <QScriptClass>
          ^~~~~~~~~~~~~~
compilation terminated.
...

time="2019-08-08T21:33:22+03:00" level=info msg="installing full qt/purchasing"
github.com/therecipe/qt/purchasing
# github.com/therecipe/qt/purchasing
purchasing.cpp:19:10: fatal error: QInAppProduct: No such file or directory
 #include <QInAppProduct>
          ^~~~~~~~~~~~~~~
compilation terminated.

time="2019-08-08T21:33:25+03:00" level=info msg="installing full qt/datavisualization    [GPLv3]"
github.com/therecipe/qt/datavisualization
# github.com/therecipe/qt/datavisualization
datavisualization.cpp:9:10: fatal error: Q3DBars: No such file or directory
 #include <Q3DBars>
          ^~~~~~~~~
compilation terminated.

time="2019-08-08T21:33:56+03:00" level=info msg="installing full qt/charts               [GPLv3]"
github.com/therecipe/qt/charts
# github.com/therecipe/qt/charts
charts.cpp:9:10: fatal error: QAbstractAxis: No such file or directory
 #include <QAbstractAxis>
          ^~~~~~~~~~~~~~~
compilation terminated.

time="2019-08-08T21:34:55+03:00" level=info msg="installing full qt/virtualkeyboard      [GPLv3]"
github.com/therecipe/qt/virtualkeyboard
# github.com/therecipe/qt/virtualkeyboard
virtualkeyboard.cpp:43:10: fatal error: QVirtualKeyboardAbstractInputMethod: No such file or directory
 #include <QVirtualKeyboardAbstractInputMethod>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
...

time="2019-08-08T21:35:24+03:00" level=warning msg="failed to install:"
time="2019-08-08T21:35:24+03:00" level=warning msg=script
time="2019-08-08T21:35:24+03:00" level=warning msg=scripttools
time="2019-08-08T21:35:24+03:00" level=warning msg=purchasing
time="2019-08-08T21:35:24+03:00" level=warning msg=datavisualization
time="2019-08-08T21:35:25+03:00" level=warning msg=charts
time="2019-08-08T21:35:25+03:00" level=warning msg=virtualkeyboard
...
```

**Comment by dballard** [comment]
I clearly picked the wrong day (yesterday) to try and set up a new windows dev environment. I am also seeing this, still today, using QT 5.13 installed into C:/Qt and msys2 

I updated the qtsetup tool and therecipe/qt repo to include the above change.

```
lord_@quartz MINGW64 /c/Qt
$ QT_QMAKE_DIR=/c/Qt/5.13.0/mingw73_64/bin/ qtsetup.exe test
time="2019-08-08T20:30:47-05:00" level=info msg="running: 'qtsetup test windows' [docker=false] [vagrant=false]"
time="2019-08-08T20:30:47-05:00" level=info msg="testing showcases\\wallet"
time="2019-08-08T20:31:36-05:00" level=error msg="failed to run command" _func=RunCmd cmd="go build -p 8 -v -ldflags=all=\"-s\" \"-w\" \"-H=windowsgui\" -o C:\\Users\\lord_\\go\\src\\github.com\\therecipe\\qt\\internal\\examples\\showcases\\wallet\\deploy\\windows\\wallet.exe -tags=\"minimal\"" dir="C:\\Users\\lord_\\go\\src\\github.com\\therecipe\\qt\\internal\\examples\\showcases\\wallet" env="HOME=C:\\msys64\\home\\lord_ NUMBER_OF_PROCESSORS=8 PROCESSOR_ARCHITECTURE=AMD64 GOARCH=amd64 TEMP=C:\\msys64\\tmp CONFIG_SITE=C:/msys64/mingw64/etc/config.site FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer tmp=C:\\Users\\lord_\\AppData\\Local\\Temp GO111MODULE=off ORIGINAL_TMP=C:/Users/lord_/AppData/Local/Temp ProgramData=C:\\ProgramData USER=lord_ USERDOMAIN_ROAMINGPROFILE=QUARTZ ACLOCAL_PATH=C:\\msys64\\mingw64\\share\\aclocal;C:\\msys64\\usr\\share\\aclocal MINGW_PACKAGE_PREFIX=mingw-w64-x86_64 SYSTEMROOT=C:\\WINDOWS USERNAME=lord_ ProgramFiles(x86)=C:\\Program Files (x86) ProgramW6432=C:\\Program Files !;=;\\ COMPUTERNAME=QUARTZ MSYSTEM_CARCH=x86_64 PROCESSOR_LEVEL=6 PUBLIC=C:\\Users\\Public SYSTEMDRIVE=C: TMP=C:\\msys64\\tmp FPS_BROWSER_USER_PROFILE_STRING=Default MINGW_PREFIX=C:/msys64/mingw64 PROCESSOR_REVISION=8e0a PSModulePath=C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules SHLVL=1 USERDOMAIN=QUARTZ temp=C:\\Users\\lord_\\AppData\\Local\\Temp PATH=C:\\msys64\\mingw64\\bin;C:\\msys64\\mingw64\\bin;C:\\msys64\\usr\\local\\bin;C:\\msys64\\usr\\bin;C:\\msys64\\usr\\bin;C:\\Windows\\System32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\msys64\\usr\\bin\\site_perl;C:\\msys64\\usr\\bin\\vendor_perl;C:\\msys64\\usr\\bin\\core_perl;C:\\Users\\lord_\\go\\bin\\;C:\\Qt\\Tools\\mingw730_64\\bin\\;C:\\Qt\\5.13.0\\mingw730_64\\bin LANG=en_US.UTF-8 ORIGINAL_PATH=C:\\Windows\\System32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\ PS1=\\[\\e]0;\\w\\a\\]\\n\\[\\e[32m\\]\\u@\\h \\[\\e[35m\\]$MSYSTEM\\[\\e[0m\\] \\[\\e[33m\\]\\w\\[\\e[0m\\]\\n\\$  MINTTY_SHORTCUT=C:/Users/lord_/AppData/Roaming/Microsoft/Internet Explorer/Quick Launch/User Pinned/TaskBar/MSYS2 terminal.lnk PWD=C:/Qt QT_QMAKE_DIR=C:/Qt/5.13.0/mingw73_64/bin/ HOMEDRIVE=C: PRINTER=OneNote LOGONSERVER=\\\\QUARTZ SESSIONNAME=Console SHELL=C:/msys64/usr/bin/bash TERM=xterm QT_DIR=C:\\Qt COMSPEC=C:\\WINDOWS\\system32\\cmd.exe ORIGINAL_TEMP=C:/Users/lord_/AppData/Local/Temp OS=Windows_NT PROGRAMFILES=C:\\Program Files MANPATH=C:\\msys64\\mingw64\\local\\man;C:\\msys64\\mingw64\\share\\man;C:\\msys64\\usr\\local\\man;C:\\msys64\\usr\\share\\man;C:\\msys64\\usr\\man;C:\\msys64\\share\\man MSYSTEM=MINGW64 MSYSTEM_PREFIX=C:/msys64/mingw64 USERPROFILE=C:\\Users\\lord_ GOOS=windows CGO_ENABLED=1 COMMONPROGRAMFILES=C:\\Program Files\\Common Files CommonProgramW6432=C:\\Program Files\\Common Files DriverData=C:\\Windows\\System32\\Drivers\\DriverData HOSTNAME=quartz _=C:/Users/lord_/go/bin/qtsetup.exe ALLUSERSPROFILE=C:\\ProgramData HOMEPATH=\\Users\\lord_ LOCALAPPDATA=C:\\Users\\lord_\\AppData\\Local PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC GOPATH=C:\\Users\\lord_\\go INFOPATH=C:\\msys64\\usr\\local\\info;C:\\msys64\\usr\\share\\info;C:\\msys64\\usr\\info;C:\\msys64\\share\\info OneDrive=C:\\Users\\lord_\\OneDrive WINDIR=C:\\WINDOWS QT_VERSION=5.13.0 GOROOT=c:\\go APPDATA=C:\\Users\\lord_\\AppData\\Roaming MSYSTEM_CHOST=x86_64-w64-mingw32 OLDPWD=C:/msys64/home/lord_ CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files MINGW_CHOST=x86_64-w64-mingw32 PKG_CONFIG_PATH=C:\\msys64\\mingw64\\lib\\pkgconfig;C:\\msys64\\mingw64\\share\\pkgconfig PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 10, GenuineIntel" error="exit status 2" name="build for windows on windows"
github.com/therecipe/qt/internal/examples/showcases/wallet/dashboard
github.com/therecipe/qt/internal/examples/showcases/wallet/hosting
github.com/therecipe/qt/internal/examples/showcases/wallet/assets
github.com/therecipe/qt/core
# github.com/therecipe/qt/internal/examples/showcases/wallet/hosting
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Gui
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Qml
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Network
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Core
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lqtmain
collect2.exe: error: ld returned 1 exit status
# github.com/therecipe/qt/internal/examples/showcases/wallet/dashboard
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Gui
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Qml
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Network
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Core
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lqtmain
collect2.exe: error: ld returned 1 exit status
# github.com/therecipe/qt/internal/examples/showcases/wallet/assets
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Gui
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Qml
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Network
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Core
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lqtmain
collect2.exe: error: ld returned 1 exit status
# github.com/therecipe/qt/core
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Svg
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5QuickWidgets
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Widgets
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Quick
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Gui
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Qml
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Network
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Core
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lqtmain
collect2.exe: error: ld returned 1 exit status
```

**Comment by walkskyer** [comment]
It works! THX @therecipe

**Comment by walkskyer** [comment]
Thanks!@therecipe. But when I run the qtsetup, I get the same problem like @Hanan-Natan

**Comment by therecipe** [comment]
@Hanan-Natan @walkskyer 
Did you opt-in into these modules while installing Qt?
Because these modules are either deprecated (script and scripttools) or GPL licensed (purchasing, charts, ...) and so the Qt installer is not installing them by default.
If you don't want to make use of these modules, then you can just ignore the warnings during the setup for now.

It's planned to automatically detect which modules are available in the future, so that these warnings don't pop up, but I haven't had time to look into that yet https://github.com/therecipe/qt/issues/820#issuecomment-480546995

@dballard 
Sorry, I fixed some of these issues with https://github.com/therecipe/qt/commit/0b997e8d18a6f416bf646ee24338413c33ba4237 now.
But msys2 still only supports Qt 5.12.4, so you will probably need to manually export `QT_API=5.13.0` before building your application if you run into any api issues.

**Comment by Hanan-Natan** [comment]
@therecipe I didn't manually opt-in into these modules while following the default installation procedure (using the official Qt installer for windows).
My problem is solved as i was able to build the application i wanted.

**Comment by walkskyer** [comment]
@therecipe Got it! THX! ^_^

**Comment by dballard** [comment]
I'm still seeing this trying to use qt 5.13 and recent therecipe on windows
I tried following hte install instructions again, reinstalling qt, using the c:\go\bin\qtenv.bat from cmd or using msys. Always the same linking problem

```
c:\Go\bin>qtenv.bat
Setting up environment for Qt usage...

C:\Qt\5.13.0\mingw73_64>qtsetup test
time="2020-01-17T16:42:20-05:00" level=info msg="running: 'qtsetup test windows' [docker=false] [vagrant=false]"
time="2020-01-17T16:42:20-05:00" level=info msg="testing qml\\gallery"
time="2020-01-17T16:42:54-05:00" level=error msg="failed to run command" _func=RunCmd cmd="go build -p 8 -v -ldflags=all=\"-s\" \"-w\" \"-H=windowsgui\" -trimpath -o C:\\Users\\lord_\\go\\src\\github.com\\therecipe\\qt\\internal\\examples\\qml\\gallery\\deploy\\windows\\gallery.exe -tags=minimal" dir="C:\\Users\\lord_\\go\\src\\github.com\\therecipe\\qt\\internal\\examples\\qml\\gallery" env="USERDOMAIN=QUARTZ GOOS=windows TMP=C:\\Users\\lord_\\AppData\\Local\\Temp APPDATA=C:\\Users\\lord_\\AppData\\Roaming GO111MODULE=off HOMEPATH=\\Users\\lord_ LOGONSERVER=\\\\QUARTZ ProgramFiles(x86)=C:\\Program Files (x86) GOROOT=c:\\go TEMP=C:\\Users\\lord_\\AppData\\Local\\Temp CommonProgramFiles=C:\\Program Files\\Common Files PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC SystemRoot=C:\\WINDOWS GOARCH=amd64 LOCALAPPDATA=C:\\Users\\lord_\\AppData\\Local PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 10, GenuineIntel SESSIONNAME=Console USERNAME=lord_ PATH=C:\\Qt\\Tools\\mingw730_64\\bin;C:\\Qt\\5.13.0\\mingw73_64\\bin;C:/Qt/Tools/mingw730_64\\bin;C:\\Qt\\5.13.0\\mingw73_64\\bin;C:/Qt/Tools/mingw730_64\\bin;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Program Files\\PuTTY\\;C:\\Go\\bin;C:\\Qt\\5.13.0\\mingw73_64\\bin;C:\\Qt\\Tools\\mingw73_64\\bin;C:\\Program Files\\Git\\cmd;C:\\Users\\lord_\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\lord_\\go\\bin;C:\\Qt\\5.13.0\\mingw73_64\\bin;C:\\Qt\\Tools\\mingw530_64\\bin; GOPATH=C:\\Users\\lord_\\go CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files ComSpec=C:\\WINDOWS\\system32\\cmd.exe DriverData=C:\\Windows\\System32\\Drivers\\DriverData PROCESSOR_LEVEL=6 USERPROFILE=C:\\Users\\lord_ QT_VERSION=5.13.0 =::=::\\ PROCESSOR_ARCHITECTURE=AMD64 ProgramFiles=C:\\Program Files ProgramW6432=C:\\Program Files PROMPT=$P$G PUBLIC=C:\\Users\\Public QT_API=5.13.0 SystemDrive=C: COMPUTERNAME=QUARTZ FPS_BROWSER_USER_PROFILE_STRING=Default NUMBER_OF_PROCESSORS=8 OneDrive=C:\\Users\\lord_\\OneDrive OS=Windows_NT CommonProgramW6432=C:\\Program Files\\Common Files PROCESSOR_REVISION=8e0a ProgramData=C:\\ProgramData windir=C:\\WINDOWS QT_QMAKE_DIR=C:\\Qt\\5.13.0\\mingw73_64\\bin CGO_ENABLED=1 ALLUSERSPROFILE=C:\\ProgramData FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer HOMEDRIVE=C: Path=C:\\Qt\\5.13.0\\mingw73_64\\bin;C:/Qt/Tools/mingw730_64\\bin;C:\\Qt\\5.13.0\\mingw73_64\\bin;C:/Qt/Tools/mingw730_64\\bin;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Program Files\\PuTTY\\;C:\\Go\\bin;C:\\Qt\\5.13.0\\mingw73_64\\bin;C:\\Qt\\Tools\\mingw73_64\\bin;C:\\Program Files\\Git\\cmd;C:\\Users\\lord_\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\lord_\\go\\bin;C:\\Qt\\5.13.0\\mingw73_64\\bin;C:\\Qt\\Tools\\mingw530_64\\bin; PSModulePath=C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules QT_DIR=C:\\Qt USERDOMAIN_ROAMINGPROFILE=QUARTZ" error="exit status 2" name="build for windows on windows"
github.com/therecipe/qt/quickcontrols2
github.com/therecipe/qt/qml
# github.com/therecipe/qt/quickcontrols2
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5QuickControls2
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5QuickWidgets
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Quick
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Widgets
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Gui
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Qml
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Network
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Core
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lqtmain
collect2.exe: error: ld returned 1 exit status
# github.com/therecipe/qt/qml
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Gui
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Qml
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Network
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Core
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lqtmain
collect2.exe: error: ld returned 1 exit status
```

with therecipe/qt  2b818d970888dab6bbf6aa2702bc28c1e6fbdb83   Fri Jan 3 05:10:36 2020

**Comment by blakeyi** [comment]
i have the same problem, but i finally solved it, the reason is i run the qtsetup in the gitbash which could use the wrong ld.exe, so when i run this command in cmd, it succeed
