### ISSUE TITLE
Passing arguments to widgets.NewQApplication results in a segment violation.

### ISSUE THREAD

**Issue by pekim** [therecipe/qt#96]
```go
package main

import (
	"os"

	"github.com/therecipe/qt/widgets"
)

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)
	widgets.QApplication_Exec()
}
```

Running this with command line arguments result in a segment violation.
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xffffffffffffffc0 pc=0x7f1248cf7a44]

runtime stack:
runtime.throw(0x19935bc, 0x2a)
	/usr/local/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x2cc

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x14e2bb0, 0xc42005bef8, 0xc400000000)
	/usr/local/go/src/runtime/cgocall.go:131 +0x110 fp=0xc42005bec8 sp=0xc42005be88
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec(0x0)
	github.com/therecipe/qt/widgets/_obj/_cgo_gotypes.go:16812 +0x49 fp=0xc42005bef8 sp=0xc42005bec8
github.com/therecipe/qt/widgets.QApplication_Exec(0x2)
	/home/mike/go/src/github.com/therecipe/qt/widgets/widgets.go:19865 +0x22 fp=0xc42005bf10 sp=0xc42005bef8
main.main()
	/home/mike/go/src/github.com/pekim/mixlac-qt-go/mixlac.go:11 +0x56 fp=0xc42005bf48 sp=0xc42005bf10
runtime.main()
	/usr/local/go/src/runtime/proc.go:183 +0x1f4 fp=0xc42005bfa0 sp=0xc42005bf48
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42005bfa8 sp=0xc42005bfa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1
```

Looking at `widgets.NewQApplication`, I wonder if it's the freeing of `argC` that's the problem?
```go
func NewQApplication(argc int, argv []string) *QApplication {
	var argvC = C.CString(strings.Join(argv, "|"))
        defer C.free(unsafe.Pointer(argvC))
        var tmpValue = NewQApplicationFromPointer(C.QApplication_NewQApplication(C.int(int32(argc)), argvC))
        if !qt.ExistsSignal(fmt.Sprint(tmpValue.Pointer()), "QObject::destroyed") {
                tmpValue.ConnectDestroyed(func(*core.QObject) { tmpValue.SetPointer(nil) })
        }
        return tmpValue
}
```
http://doc.qt.io/qt-5.7/qapplication.html#QApplication states 
> Warning: The data referred to by argc and argv must stay valid for the entire lifetime of the QApplication object. In addition, argc must be greater than zero and argv must contain at least one valid character string.

It's the _entire lifetime_ bit that bothers me.

**Comment by therecipe** [comment]
Hey

It should be fixed with https://github.com/therecipe/qt/commit/1ee5e1199c2067a1f2a3b635f1ddf8395f4f640d
Like you said, there was a problem with the lifetime of `argv`.

But the problem was one the C++ side, where `argc` and `argv` are copied and made static to extend their lifetime.

I simply forgot to make `argv` static, which caused the issue.

This is what it looks now:

```C++
void* QApplication_NewQApplication(int argc, char* argv)
{
	QList<QByteArray> aList = QByteArray(argv).split('|');
	static char** argvs = static_cast<char**>(malloc(argc * sizeof(char*)));
	static int argcs = argc;
	for (int i = 0; i < argc; i++)
		argvs[i] = const_cast<char*>(aList[i].constData());

	return new MyQApplication(argcs, argvs);
}
```

**Comment by pekim** [comment]
While there's no longer a segv, unfortunately it still doesn't appear to be quite right.

```go
	app := widgets.NewQApplication(len(os.Args), os.Args)
	fmt.Println(len(os.Args), os.Args, strings.Join(os.Args, "|"))
	fmt.Println(len(app.Arguments()), app.Arguments(), strings.Join(app.Arguments(), "|"))
```
The number of arguments is correct, but their values are not.
```
4 [./mixlac -t abc -f] ./mixlac|-t|abc|-f
4 [Ќ�   1] Ќ�|||1
```

**Comment by therecipe** [comment]
Strange, it works for me on macOS with `go version go1.7.1 darwin/amd64`

I did test it with `go build -o mixlac && ./mixlac -t abc -f`

and got:

```
4 [./mixlac -t abc -f] ./mixlac|-t|abc|-f
4 [./mixlac -t abc -f] ./mixlac|-t|abc|-f
```

with:

```go
package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/therecipe/qt/widgets"
)

func main() {
	app := widgets.NewQApplication(len(os.Args), os.Args)
	fmt.Println(len(os.Args), os.Args, strings.Join(os.Args, "|"))
	fmt.Println(len(app.Arguments()), app.Arguments(), strings.Join(app.Arguments(), "|"))
}
```

What Go version do you use?
Are you on macOS or Linux?
How did you compile and start the binary?
Did you use the prebuild package or do you use Homebrew / Pkg-Config / ... ?

You can also use `$GOPATH/bin/qtsetup check` to get some infos about your env.

**Comment by pekim** [comment]
Go - 1.7.1
OS - Linux (Ubuntu 14.04)
Build and run - just like you, with `go build ...` (not with qtdeploy)
Installation of qt - prebuilt package

Output of `qtsetup check`
```
INFO[0000] running setup/check desktop                  
INFO[0000] GOOS: linux                                  
INFO[0000] GOARCH: amd64                                
INFO[0000] GOVERSION: go1.7.1                           
INFO[0000] GOROOT: /usr/local/go                        
INFO[0000] GOPATH: /home/mike/go                        
INFO[0000] HASH: 1ee5e1199c2067a1f2a3b635f1ddf8395f4f640d 
INFO[0000] QT_DIR: /home/mike/Qt                        
INFO[0000] QT_STUB: false                               
INFO[0000] Distro: ubuntu                               
INFO[0000] QT_PKG_CONFIG:                               
INFO[0000] UsePkgConfig: false             
```

**Comment by therecipe** [comment]
I got this one Linux Mint 18

```
4 [./mixlac -t abc -f] ./mixlac|-t|abc|-f
6 [     ] |||||
```

I will look into this.

**Comment by therecipe** [comment]
I think I got it. https://github.com/therecipe/qt/commit/cda58d725b8ea7665f8c342687d79adea5f0eb43

The argument list was freed on the C++ side, because I didn't create a proper char**.

**Comment by pekim** [comment]
Yes, that all seems good now. Thanks for persevering.
